language: generic
env:
  global:
    - ORG="devonfw"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_SOURCE="cobigen"
    - REPO_DEST="cobigen.wiki"
    - REPO_CONSOLIDATE="devonfw-guide"
    - GH_REPO_SOURCE="github.com/${ORG}/${REPO_SOURCE}.git"
    - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
    - GH_REPO_CONSOLIDATE="github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    - secure: LaDZLvPaW1O59PbNnkNo/e18/fsdPDmlS5dF2hfbljAgYfdCwyiJbCAoUMyM1NcAHQ/28zNWaVP8u5cADNbQGA3X4FYSfCRTaq5Ikm0AOObb/JQrhvMMkSfzhM1AU/oglUfYtwcBWdCEhUrsX97tZPoVCjlaqrjiBWYDyp70NAxrKpXnNEiy4GRPUHSy9WIgfYcG5Y2V1mZHWmkurhtUL6Xy2SL6Uq9/VazqlI6Yxry9AXpZHQynjQlmbMkGPC71AIcb8vfY47a/n7mwnztzfTuRUnIZKyetIiT0GHPErg0S2IBGk1LTxBd9mFk1lKCybbUv1G7ROxrYaw1yeRwcsb7tLRwX8QT9HfcDSIzKO7fr92HsGzSsPrjsCObGPxLPPUTqSC+DDIU1S2KChqjLXuq6AOdY0qWAuUOhtp+ksb1oqEQnWowKfJ17Z5ijuC7alPAdlHqlN9BY/AYkyUpr1azOJuBKwG1uMkhxTjLKnu8HHZ0onkcwkKwTjl+FEfaIWBqiIFl/2VPSZ+jLlcccgzW3emVI2EzZFDTX9wIzgE0BJx1ZV3aQQ74gbVNngDyl9BS2ncSIG2YCC6gJfSfYyGl00cctHdq9QtR61XJdklQmAw2vjdq4me3WT7lPx1BeAkxZL1l7xmUovt7kpdd9NDD26b8a8ITLqgQ377RZ3nI=
stages:
  - name: Documentation
    if: (branch = master) AND (type = push)
jobs:
  include:
    - stage: Documentation
      if: (type = push) AND (branch = master)
      script:
        # Clone repositories
        - git clone -b master --single-branch https://${GH_REPO_SOURCE}
        - git clone https://${GH_REPO_DEST}
        - git clone https://${GH_REPO_CONSOLIDATE}
        # Update wiki repository with documentation folder contents
        - yes | cp -rf ${REPO_SOURCE}/documentation/* ${REPO_DEST}/
        - cd ${REPO_DEST}
        - grep -lr "link:[a-zA-Z0-9_.-]*.asciidoc.*" .| xargs -r sed -i "s/.asciidoc//g"
        # Terminate Travis CI build when no changes detected
        - |
          if git diff-index --quiet HEAD && [ ! -n "$(git status -s)" ]; then 
            set +e 
            pkill -9 -P $$ &> /dev/null || true 
            exit 0
          else 
            git config user.email ${EMAIL}
            git config user.name ${USER}
            git status
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${GITHUB_TOKEN}@${GH_REPO_DEST}"
            git push origin-wiki master
            cd ../${REPO_CONSOLIDATE}
            if [ ! -d ${REPO_DEST} ]; then git submodule add https://${GH_REPO_DEST}; fi;
            git submodule init
            git submodule update --recursive --remote
            cd ${REPO_DEST}
            git checkout master
            git pull
            cd ..
            git add .
            git commit -m "${REPO_SOURCE} documentation | Travis CI build number $TRAVIS_BUILD_NUMBER"
            git remote add origin-wiki "https://${GITHUB_TOKEN}@${GH_REPO_CONSOLIDATE}"
            git push origin-wiki master
          fi
