language: generic
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
    - "$HOME/.m2/repository"
services:
  - xvfb
env:
  global:
    - ORG="devonfw"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_SOURCE="cobigen"
    - REPO_DEST="cobigen.wiki"
    - REPO_CONSOLIDATE="devonfw-guide"
    - GH_REPO_SOURCE="github.com/${ORG}/${REPO_SOURCE}.git"
    - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
    - GH_REPO_CONSOLIDATE="github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    - secure: LaDZLvPaW1O59PbNnkNo/e18/fsdPDmlS5dF2hfbljAgYfdCwyiJbCAoUMyM1NcAHQ/28zNWaVP8u5cADNbQGA3X4FYSfCRTaq5Ikm0AOObb/JQrhvMMkSfzhM1AU/oglUfYtwcBWdCEhUrsX97tZPoVCjlaqrjiBWYDyp70NAxrKpXnNEiy4GRPUHSy9WIgfYcG5Y2V1mZHWmkurhtUL6Xy2SL6Uq9/VazqlI6Yxry9AXpZHQynjQlmbMkGPC71AIcb8vfY47a/n7mwnztzfTuRUnIZKyetIiT0GHPErg0S2IBGk1LTxBd9mFk1lKCybbUv1G7ROxrYaw1yeRwcsb7tLRwX8QT9HfcDSIzKO7fr92HsGzSsPrjsCObGPxLPPUTqSC+DDIU1S2KChqjLXuq6AOdY0qWAuUOhtp+ksb1oqEQnWowKfJ17Z5ijuC7alPAdlHqlN9BY/AYkyUpr1azOJuBKwG1uMkhxTjLKnu8HHZ0onkcwkKwTjl+FEfaIWBqiIFl/2VPSZ+jLlcccgzW3emVI2EzZFDTX9wIzgE0BJx1ZV3aQQ74gbVNngDyl9BS2ncSIG2YCC6gJfSfYyGl00cctHdq9QtR61XJdklQmAw2vjdq4me3WT7lPx1BeAkxZL1l7xmUovt7kpdd9NDD26b8a8ITLqgQ377RZ3nI=
    - secure: jjf+2LuRPALUCWMqAchoddsWZqJFOc4HpXxYi0IlOitAlS249bwqTCuesgDKLpecqKE9ttSlOFkFdY02VKl5dxQg6ndxghsqrwWhYwZ0oYyrLSJ+yaR4IYyyE8KNC+77eO5h9zh8Cya4d7XiNiPB6F18HezSmlLXQClDB5qgANwJYCFnyuD8EutkDQxLCajOHrj6OEDnXb0x4x144PA/CcAAaseghIRNdsWSQbx0Jh4+25vQln8gctbc3jsnd1M2v//xtmvGDUrAovL2p9fl5RL0BPTQnm0YtBMwAoGmVy5fBKRLR36HTL8Jff0qAO+RTcMDL/CN4BjbT/1Fk+b0MZjnm736eH4uA+9XwsnRSHw8/t1t7WwJp0/Iap8aqBEBQea8Ca+vQCPdsol14I9YbH4zBf8LEZ6CCb9LkFG90bk+V1UlDBqzuTSTIaWsASkH1ytfaqjLuSekLZ3Mfq/VJRfUfnnhLpQLbexLhCRlL+xqrlIp4zg0iT2nuPhgF31H0XL5sxtoWHPBdwP5QL2rGz8pphA3N03HSKUk4x69uX824+Hhe/+yDdNI8TsxSEd0gajPmoZz6PqQejHTDMd/HPLvGDIfqDEM5l7nndTz4crmBitIR1JrICvqKov/k8d0Ne4SAHsQjzg/EG4sYKF2Jua4meuy0R2AI6mXnP/kcIY=
    - secure: ax002sOgbQova/2ofIFEDKbUssJiFDbyDLQzYbAHRLKB06KpKx4yCRk6OicTC7cD9iMe0Ftm82+ZrL9Pt1CMqvZX/CVo+qxVV6Pj6LPHZvSssyzp3HCHcaHo3Wss/+GlEwkR7xV5c2wKzVoRcOSmVwonBR7Xr+ivOC04kamDWnart+P1Iwr7CL9zQo8g7m9kq+hCjmdj000pd9DncgJoZN/CS58HOaRbHZdVD9CRgxVi6lYpldtpAQo2YQUARgc4R/+vTozvNSyLKxEEbylWMifn0cND/NjJd2pk7WGVUiqSPdGF6ByOCXYGa6eLjc9Zp2N9iCPdXszrw+MuC8g0fm9/wXueNO2Fa13oO3hWhi3uxDO9XZ6QRjW+6OyrqSb6Cm2F3T0In07GHNXcfr/PkzDGoXJGCymYn/NYJQhI+kNbaVq+Pz0xisOl79By1zcJuc16PQDoMFZN5vpcqW8O/IK9XhNxok8eW5bH+/r+cgRWM3ZUSxamMgH4SuWz7iotLtKlyHOHpMjTb0s/5nEY5OHbgTtaXvAmwX74LiL/FS49o7lbYfbtMsPySghIUrsaJ936gBCmhS1aWuF/K2ew9jkZT6m3eWZ7+H6/hT49C17jnmey89J7PGNwrkQJtNPAic/MxiyHTpzD1/fE9qw4+VBssvZPH+abokMxF8e1joI=
    - secure: XTEsjRiKbOWMF4M4SGduuxukYsRS+Lh41JU3ABVTS2zWpj21MXxzBc9T4o9fmbwRaPh8O3uDrBcG4Qp3BidI6JjVgZWKx7kNQsuSIsJH3Tz5eTptUp0buLKqa06lSHJarvTvHjcpNbgzlzby/ivmvo5kCrp3ekpRZAz70Tp8FubMSjJ6pT0LmOYVugveOnRAzraPoDvUbc4vWl2oKNzeIW++Gg3iBvOr+//6/AEJc2K5zdSCtm6oNleA4TRCT/G/Lg8XP7DSnDtHBAVx73knQihYjG8UhbFL7BCzBwpApwj2X6z6LVWPPCSe68J6P7gzqCYqz6Es2UomtFoMb/TFkhST/UFmqdPq2mBWrrsHThyLNAyUoGenZDQHTWfPv76B9F7uCvju3fwjPDhIsGWFbZWYBBYie1pzhngJYcICC6Yi1qhcqBSl73eHj0dubQuiW8zYrbY1Xj9KqRKF6UxRQru/DwRf1Ao/FiU1Y3CfTpJZcLedS5Wy8CgnkVLcK1SxX+UVc6VCuH9K9IrbbZM/Hx0HBDI/g4B8BN7+wBO68OTYmaALVlRdGTvfdCbUHsWGB8Zf/sqVIH2nv7XB6nojG6W1ANc3P/45LpZhmDGb1iwZ0rT+1t49Me0Cl4+cyQnPwlr8W5K9wHu0iVdtg/l0d9Q95bjhO6TJU/S6zDsusn0=
    - secure: kwP9fFcGxzE1usORJH0zRFlzxvi9LOC+FcgMbFxU0GOqkEAFFwOdnUoelk26/73wRuJpPww2W0pAFPYO5LSa5HjTeEdWDHrSadbn2L2B9lZY3rYI3ZLrXSMi1rsC2rtZnEZbs08BzmXu/u9YSgiArijaUTgObGXzTAtIoem+Mj8za7bVYznbc5YEFk4/NGzxPiw7DmtNLtMd9F0fYrOLslpDoXgCTqYfMweUCJ2ZnF7zfOjtL7pc8RA2MN0CEZUGZ9/isUQ5FUE5GSl+HKP+NHIhpx+sMWOGLIu2NuMLPEMiv6W8m4n814CRhf9yuDKKuEDhvhF06hQpRpnAGwaIxwXLIhwvndASa/rsy1gguvNYCWxi0dSIYTdHRr80iiJFtAWTP/6ddhO+E5vltRrclTsYnpQ2Im8Oz51pzP2mQ8iax4cY+kqAPibpF/k6qVc6YCIHykWQQbp0iVGDquhNqoEYKc/Oyd6wOqSzeGkme8M+pk3tQP7Eb9Ffyve5PdZauuz7bohSJN5CII+pydVJCnTThxejnDiNDYWjEur6LSdfBlMqVUsBvmH9wQ0nCrlKcx+5H+i3nqWImrY+DfoVeyDS7HVIZBj1NZhVia3AnN74n40hxY1NuQ//QkUu2p9FrweNCjc/tTf171LxKs3/0my3QvLgeOdvHD0Jq8mkMX8=
stages:
  - name: Documentation
    if: (branch = master) AND (type != pull_request) AND (fork = false)
  - name: Build & Test
    if: (branch != gh-pages) AND (branch != dev_oomph_setup) AND (tag IS blank)
  - name: Deploy
    if: (branch != master) AND (branch != gh-pages) AND (branch != dev_oomph_setup) AND (type != pull_request) AND (fork = false) AND (tag IS blank)
jobs:
  include:
    - stage: Build & Test
      script: ./scripts/travis-build-test.sh
    - stage: Deploy
      script: ./scripts/travis-deploy.sh
    - stage: Documentation
      script: ./scripts/travis-sync-docs.sh
