language: generic
jdk:
  - openjdk8
  - openjdk11
cache:
  directories:
    - "$HOME/.m2/repository"
install: true
addons:
  apt:
    packages:
      - metacity
env:
  global:
    - DISPLAY=:99.0
    - ORG="devonfw"
    - EMAIL="icsddevonfwsupport.apps2@capgemini.com"
    - REPO_SOURCE="cobigen"
    - REPO_DEST="cobigen.wiki"
    - REPO_CONSOLIDATE="devonfw-guide"
    - GH_REPO_SOURCE="github.com/${ORG}/${REPO_SOURCE}.git"
    - GH_REPO_DEST="github.com/${ORG}/${REPO_DEST}.git"
    - GH_REPO_CONSOLIDATE="github.com/${ORG}/${REPO_CONSOLIDATE}.git"
    - secure: LaDZLvPaW1O59PbNnkNo/e18/fsdPDmlS5dF2hfbljAgYfdCwyiJbCAoUMyM1NcAHQ/28zNWaVP8u5cADNbQGA3X4FYSfCRTaq5Ikm0AOObb/JQrhvMMkSfzhM1AU/oglUfYtwcBWdCEhUrsX97tZPoVCjlaqrjiBWYDyp70NAxrKpXnNEiy4GRPUHSy9WIgfYcG5Y2V1mZHWmkurhtUL6Xy2SL6Uq9/VazqlI6Yxry9AXpZHQynjQlmbMkGPC71AIcb8vfY47a/n7mwnztzfTuRUnIZKyetIiT0GHPErg0S2IBGk1LTxBd9mFk1lKCybbUv1G7ROxrYaw1yeRwcsb7tLRwX8QT9HfcDSIzKO7fr92HsGzSsPrjsCObGPxLPPUTqSC+DDIU1S2KChqjLXuq6AOdY0qWAuUOhtp+ksb1oqEQnWowKfJ17Z5ijuC7alPAdlHqlN9BY/AYkyUpr1azOJuBKwG1uMkhxTjLKnu8HHZ0onkcwkKwTjl+FEfaIWBqiIFl/2VPSZ+jLlcccgzW3emVI2EzZFDTX9wIzgE0BJx1ZV3aQQ74gbVNngDyl9BS2ncSIG2YCC6gJfSfYyGl00cctHdq9QtR61XJdklQmAw2vjdq4me3WT7lPx1BeAkxZL1l7xmUovt7kpdd9NDD26b8a8ITLqgQ377RZ3nI=
stages:
  - name: Documentation
    if: (branch = master) AND (type = push)
  - name: Build & Test
    if: (branch != gh-pages) AND (branch != dev_oomph_setup)
  - name: Deploy
    if: (branch != master) AND (branch != gh-pages) AND (branch != dev_oomph_setup)
jobs:
  include:
    - stage: Build & Test
      before_script:
        - sh -e /etc/init.d/xvfb start
        - metacity --sm-disable --replace 2> metacity.err &
      script:
        - export
        - ./scripts/travis-build-test.sh
    - stage: Deploy
      script: ./scripts/travis-deploy.sh
    - stage: Documentation
      script: ./scripts/travis-sync-docs.sh
