# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2

defaults: &defaults
  working_directory: ~/ws
  docker:
    - image: circleci/openjdk:8-jdk
      environment:
        JVM_OPTS: -Xmx3200m

jobs:
  setup:
    <<: *defaults
    steps:
      - run:
        name: Determine Build Root
        command: |
          if [ "$CIRCLE_BRANCH" == "master" ]; then
            echo 'export BUILD_ROOT=""' >> $BASH_ENV
          elif [ "$CIRCLE_BRANCH" == "dev_eclipseplugin" ]; then
            echo 'export BUILD_ROOT="cobigen-eclipse"' >> $BASH_ENV
          elif [ "$CIRCLE_BRANCH" == "dev_mavenplugin" ]; then
            echo 'export BUILD_ROOT="cobigen-maven"' >> $BASH_ENV
          elif [[ ("$CIRCLE_BRANCH" == "dev_core") || ("$CIRCLE_BRANCH" == "dev_javaplugin") || ("$CIRCLE_BRANCH" == "dev_openapiplugin") ]]; then 
            echo 'export BUILD_ROOT="${CIRCLE_BRANCH//dev_/}-parent"' >> $BASH_ENV
          elif [ "$CIRCLE_BRANCH" == "dev_htmlmerger" ]; then 
            echo 'export BUILD_ROOT="cobigen/cobigen-htmlplugin"' >> $BASH_ENV
          elif [[ ("$CIRCLE_BRANCH" == "dev_tempeng_freemarker") || ("$CIRCLE_BRANCH" == "dev_tempeng_velocity")]]; then 
            echo 'export BUILD_ROOT="cobigen/cobigen-templateengines/cobigen-${CIRCLE_BRANCH//dev_/}"' >> $BASH_ENV
            echo 'export BUILD_ROOT="${BUILD_ROOT//_/-}"' >> $BASH_ENV
          else
            echo 'export BUILD_ROOT="cobigen/cobigen-${CIRCLE_BRANCH//dev_/}"' >> $BASH_ENV
          fi
  build:
    <<: *defaults
    steps:
      - checkout
      - run: mvn clean compile -Pp2-build-stable,p2-build-mars

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
          filters:
            branches:
              ignore: gh-pages,dev_oomph_setup
      - build:
          requires:
            - setup
          filters:
            branches:
              ignore: gh-pages,dev_oomph_setup
